version: '3.7'

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_data:/jenkins_home
    networks:
      - sonarnet
networks:
  sonarnet:
    driver: bridge

